// examples/react/src/pages/BackendDemo.tsx
import { useState, useRef } from 'react'
import { SliderCaptcha, ClickCaptcha, PopupCaptcha, type SliderCaptchaInstance, type ClickCaptchaInstance, type PopupCaptchaInstance } from '@captcha/react'
import { useLocale } from '../hooks/useLocale'

export function BackendDemo() {
  const { currentLocale, t } = useLocale()
  const [backendUrl, setBackendUrl] = useState('http://localhost:3001')
  const [backendType, setBackendType] = useState<'slider' | 'click'>('slider')
  const [popupType, setPopupType] = useState<'slider' | 'click'>('slider')
  const [popupAutoClose, setPopupAutoClose] = useState(true)
  const backendRef = useRef<SliderCaptchaInstance | ClickCaptchaInstance>(null)
  const popupRef = useRef<PopupCaptchaInstance>(null)

  const checkHealth = async () => {
    try {
      const res = await fetch(`${backendUrl}/api/health`)
      const data = await res.json()
      alert(t('后端服务正常', 'Backend service is healthy') + `\n\n${JSON.stringify(data, null, 2)}`)
    } catch {
      alert(t('无法连接后端服务', 'Cannot connect to backend'))
    }
  }

  const CaptchaComponent = backendType === 'slider' ? SliderCaptcha : ClickCaptcha

  return (
    <section className="demo-section">
      <h2>🖥️ {t('后端验证演示', 'Backend Verification')}<span className="new-badge">服务端生成</span></h2>

      <div className="info-box">
        💡 {t('图片由后端服务生成，更安全可靠。需要先启动后端服务：cd server/node && pnpm dev', 'Images generated by backend server. Start server: cd server/node && pnpm dev')}
      </div>

      <div className="options">
        <div className="option-row">
          <label>{t('服务地址', 'Server URL')}:</label>
          <input type="text" value={backendUrl} onChange={(e) => setBackendUrl(e.target.value)} style={{ width: 200 }} />
        </div>
        <div className="option-row">
          <label>{t('验证码类型', 'Type')}:</label>
          <select value={backendType} onChange={(e) => setBackendType(e.target.value as 'slider' | 'click')}>
            <option value="slider">{t('滑块验证', 'Slider')}</option>
            <option value="click">{t('点击验证', 'Click')}</option>
          </select>
        </div>
      </div>

      <div className="captcha-box">
        <CaptchaComponent
          key={backendType}
          ref={backendRef as React.RefObject<SliderCaptchaInstance & ClickCaptchaInstance>}
          width={320}
          height={180}
          verifyMode="backend"
          backendVerify={{
            getCaptcha: `${backendUrl}/api/captcha?type=${backendType}`,
            verify: `${backendUrl}/api/captcha/verify`
          }}
          locale={currentLocale}
          onSuccess={() => console.log('Backend success')}
          onFail={() => console.log('Backend fail')}
        />
      </div>

      <div className="btn-group">
        <button className="btn btn-secondary" onClick={checkHealth}>
          {t('检查服务状态', 'Check Server')}
        </button>
      </div>

      <h3 style={{ marginTop: 30, marginBottom: 15 }}>{t('后端验证弹窗', 'Backend Popup')}</h3>

      <div className="options">
        <div className="option-row">
          <label>{t('验证码类型', 'Type')}:</label>
          <select value={popupType} onChange={(e) => setPopupType(e.target.value as 'slider' | 'click')}>
            <option value="slider">{t('滑块验证', 'Slider')}</option>
            <option value="click">{t('点击验证', 'Click')}</option>
          </select>
        </div>
        <div className="option-row">
          <label>{t('自动关闭', 'Auto Close')}:</label>
          <input type="checkbox" checked={popupAutoClose} onChange={(e) => setPopupAutoClose(e.target.checked)} />
        </div>
      </div>

      <div className="btn-group" style={{ marginBottom: 20 }}>
        <button className="btn btn-primary" onClick={() => popupRef.current?.show()}>
          {t('打开后端验证弹窗', 'Open Backend Popup')}
        </button>
      </div>

      <PopupCaptcha
        key={popupType}
        ref={popupRef}
        type={popupType}
        autoClose={popupAutoClose}
        captchaOptions={{
          width: 320,
          height: 180,
          locale: currentLocale,
          verifyMode: 'backend',
          backendVerify: {
            getCaptcha: `${backendUrl}/api/captcha?type=${popupType}`,
            verify: `${backendUrl}/api/captcha/verify`
          }
        }}
        onSuccess={() => console.log('Backend popup success')}
      >
        <span></span>
      </PopupCaptcha>
    </section>
  )
}

// examples/vue/src/pages/BackendDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { SliderCaptcha, ClickCaptcha, PopupCaptcha, type CaptchaStatistics } from '@captcha-pro/vue'
import { useLocale } from '../composables/useLocale'

const { currentLocale, t } = useLocale()

const backendUrl = ref('http://localhost:3001')
const config = ref({ type: 'slider' as 'slider' | 'click' })
const captchaRef = ref()
const stats = ref<CaptchaStatistics | null>(null)

const popupConfig = ref({
  type: 'slider' as 'slider' | 'click',
  autoClose: true
})
const popupRef = ref()

const checkBackendHealth = async () => {
  try {
    const res = await fetch(`${backendUrl.value}/api/health`)
    const data = await res.json()
    alert(t('后端服务正常', 'Backend service is healthy') + `\n\n${JSON.stringify(data, null, 2)}`)
  } catch {
    alert(t('无法连接后端服务，请确保已启动服务端:\ncd server/node && pnpm dev', 'Cannot connect to backend. Please start the server:\ncd server/node && pnpm dev'))
  }
}

const getData = () => {
  const data = captchaRef.value?.getData()
  console.log('Backend captcha data:', data)
  alert(t('验证数据已输出到控制台', 'Data logged to console'))
}

const updateStats = () => {
  const s = captchaRef.value?.getStatistics()
  if (s) stats.value = s
}

const showPopup = () => popupRef.value?.show()
</script>

<template>
  <section class="demo-section">
    <h2>🖥️ {{ currentLocale === 'zh-CN' ? '后端验证演示' : 'Backend Verification' }}<span class="new-badge">服务端生成</span></h2>

    <div class="info-box">
      💡 {{ currentLocale === 'zh-CN'
        ? '图片由后端服务生成，更安全可靠。需要先启动后端服务：cd server/node && pnpm dev'
        : 'Images generated by backend server for better security. Start server: cd server/node && pnpm dev' }}
    </div>

    <div class="options">
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '服务地址' : 'Server URL' }}:</label>
        <input type="text" v-model="backendUrl" style="width: 200px;">
      </div>
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="config.type">
          <option value="slider">{{ currentLocale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ currentLocale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
    </div>

    <div class="captcha-box">
      <SliderCaptcha
        v-if="config.type === 'slider'"
        ref="captchaRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{
          getCaptcha: `${backendUrl}/api/captcha?type=slider`,
          verify: `${backendUrl}/api/captcha/verify`
        }"
        :locale="currentLocale"
        @success="() => { console.log('Backend slider success'); updateStats() }"
        @fail="() => console.log('Backend slider fail')"
      />
      <ClickCaptcha
        v-else
        ref="captchaRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{
          getCaptcha: `${backendUrl}/api/captcha?type=click`,
          verify: `${backendUrl}/api/captcha/verify`
        }"
        :locale="currentLocale"
        @success="() => { console.log('Backend click success'); updateStats() }"
        @fail="() => console.log('Backend click fail')"
      />
    </div>

    <div class="btn-group">
      <button class="btn btn-secondary" @click="checkBackendHealth">{{ currentLocale === 'zh-CN' ? '检查服务状态' : 'Check Server' }}</button>
      <button class="btn btn-secondary" @click="getData">{{ currentLocale === 'zh-CN' ? '获取数据' : 'Get Data' }}</button>
    </div>

    <!-- 后端弹窗验证 -->
    <h3 style="margin-top: 30px; margin-bottom: 15px;">{{ currentLocale === 'zh-CN' ? '后端验证弹窗' : 'Backend Popup' }}</h3>

    <div class="options">
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="popupConfig.type">
          <option value="slider">{{ currentLocale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ currentLocale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '自动关闭' : 'Auto Close' }}:</label>
        <input type="checkbox" v-model="popupConfig.autoClose">
      </div>
    </div>

    <div class="btn-group" style="margin-bottom: 20px;">
      <button class="btn btn-primary" @click="showPopup">{{ currentLocale === 'zh-CN' ? '打开后端验证弹窗' : 'Open Backend Popup' }}</button>
    </div>

    <PopupCaptcha
      ref="popupRef"
      :key="popupConfig.type"
      :type="popupConfig.type"
      :auto-close="popupConfig.autoClose"
      :captcha-options="{
        width: 320,
        height: 180,
        locale: currentLocale,
        verifyMode: 'backend',
        backendVerify: {
          getCaptcha: `${backendUrl}/api/captcha?type=${popupConfig.type}`,
          verify: `${backendUrl}/api/captcha/verify`
        }
      }"
      @success="() => console.log('Backend popup success')"
    />
  </section>
</template>
