// examples/react/src/pages/InvisibleDemo.tsx
import type { ReactElement } from 'react'
import { createInvisibleCaptcha, type InvisibleCaptchaInstance } from '@captcha-pro/react'
import { useEffect, useRef, useState } from 'react'
import { Show } from "solid-js";
import { useLocale } from '../hooks/useLocale'

export function InvisibleDemo(): ReactElement {
  const { currentLocale, t } = useLocale()
  const [threshold, setThreshold] = useState(0.7)
  const [challengeType, setChallengeType] = useState<'slider' | 'click'>('slider')
  const [result, setResult] = useState<{ success: boolean, message: string, riskScore?: number } | null>(null)
  const captchaRef = useRef<InvisibleCaptchaInstance | null>(null)

  useEffect(() => {
    captchaRef.current?.destroy()
    captchaRef.current = createInvisibleCaptcha({
      el: '#invisible-trigger',
      trigger: 'click',
      riskAssessment: { threshold, behaviorCheck: { minInteractionTime: 500, trackAnalysis: true } },
      challengeType,
      challengeOptions: { width: 300, height: 170, locale: currentLocale },
      onChallenge: () => setResult({ success: false, message: t('检测到可疑行为，请完成验证', 'Suspicious behavior detected') }),
      onSuccess: () => {
        const risk = captchaRef.current?.getRiskScore() || 0
        setResult({ success: true, message: t('验证通过', 'Verification passed'), riskScore: risk })
      },
      onFail: () => setResult({ success: false, message: t('验证失败', 'Verification failed') }),
    })
    return () => captchaRef.current?.destroy()
  }, [threshold, challengeType, currentLocale, t])

  return (
    <section class="demo-section">
      <h2>
        👻
        {t('智能无感验证', 'Invisible Captcha')}
        <span class="new-badge">NEW</span>
      </h2>

      <div class="info-box">
        💡
        {' '}
        {t('基于风险评估的无感验证，仅在检测到可疑行为时才显示验证码挑战。', 'Risk-based invisible verification that only shows captcha challenge when suspicious behavior is detected.')}
      </div>

      <div class="options">
        <div class="option-row">
          <label>
            {t('风险阈值', 'Threshold')}
            :
          </label>
          <select value={threshold} onChange={e => setThreshold(Number(e.target.value))}>
            <option value={0.3}>{t('宽松 (0.3)', 'Relaxed (0.3)')}</option>
            <option value={0.5}>{t('适中 (0.5)', 'Moderate (0.5)')}</option>
            <option value={0.7}>{t('严格 (0.7)', 'Strict (0.7)')}</option>
            <option value={0.9}>{t('非常严格 (0.9)', 'Very Strict (0.9)')}</option>
          </select>
        </div>
        <div class="option-row">
          <label>
            {t('挑战类型', 'Challenge')}
            :
          </label>
          <select value={challengeType} onChange={e => setChallengeType(e.target.value as 'slider' | 'click')}>
            <option value="slider">{t('滑块验证', 'Slider')}</option>
            <option value="click">{t('点击验证', 'Click')}</option>
          </select>
        </div>
      </div>

      <div class="btn-group" style={{ "margin-bottom": '20px' }}>
        <button id="invisible-trigger" class="btn btn-primary">
          {t('点击验证', 'Click to Verify')}
        </button>
      </div>

      <Show when={result}><div class={`result ${result.success ? 'success' : 'error'}`}>
          {result.message}
          <Show when={result.riskScore !== undefined}><span>
              {' '}
              (
              {t('风险评分', 'Risk Score')}
              :
              {result.riskScore.toFixed(2)}
              )
            </span></Show>
        </div></Show>
    </section>
  )
}

// examples/vue2/src/pages/InvisibleDemo.vue
<script>
import { createInvisibleCaptcha } from '@captcha-pro/vue2'

export default {
  name: 'InvisibleDemo',
  props: {
    locale: { type: String, default: 'zh-CN' }
  },
  data() {
    return {
      threshold: 0.7,
      challengeType: 'slider',
      result: null,
      captcha: null
    }
  },
  mounted() {
    this.init()
  },
  beforeDestroy() {
    this.captcha?.destroy()
  },
  watch: {
    threshold() { this.init() },
    challengeType() { this.init() }
  },
  methods: {
    init() {
      this.captcha?.destroy()
      const self = this
      this.captcha = createInvisibleCaptcha({
        el: '#invisible-trigger',
        trigger: 'click',
        riskAssessment: { threshold: this.threshold, behaviorCheck: { minInteractionTime: 500, trackAnalysis: true } },
        challengeType: this.challengeType,
        challengeOptions: { width: 300, height: 170, locale: this.locale },
        onChallenge() {
          self.result = { success: false, message: self.locale === 'zh-CN' ? '检测到可疑行为，请完成验证' : 'Suspicious behavior detected' }
        },
        onSuccess() {
          const risk = self.captcha?.getRiskScore() || 0
          self.result = { success: true, message: self.locale === 'zh-CN' ? '验证通过' : 'Verification passed', riskScore: risk }
        },
        onFail() {
          self.result = { success: false, message: self.locale === 'zh-CN' ? '验证失败' : 'Verification failed' }
        }
      })
    }
  }
}
</script>

<template>
  <section class="demo-section">
    <h2>👻 {{ locale === 'zh-CN' ? '智能无感验证' : 'Invisible Captcha' }}<span class="new-badge">NEW</span></h2>

    <div class="info-box">
      💡 {{ locale === 'zh-CN' ? '基于风险评估的无感验证，仅在检测到可疑行为时才显示验证码挑战。' : 'Risk-based invisible verification that only shows captcha challenge when suspicious behavior is detected.' }}
    </div>

    <div class="options">
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '风险阈值' : 'Threshold' }}:</label>
        <select v-model.number="threshold">
          <option :value="0.3">{{ locale === 'zh-CN' ? '宽松 (0.3)' : 'Relaxed (0.3)' }}</option>
          <option :value="0.5">{{ locale === 'zh-CN' ? '适中 (0.5)' : 'Moderate (0.5)' }}</option>
          <option :value="0.7">{{ locale === 'zh-CN' ? '严格 (0.7)' : 'Strict (0.7)' }}</option>
          <option :value="0.9">{{ locale === 'zh-CN' ? '非常严格 (0.9)' : 'Very Strict (0.9)' }}</option>
        </select>
      </div>
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '挑战类型' : 'Challenge' }}:</label>
        <select v-model="challengeType">
          <option value="slider">{{ locale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ locale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
    </div>

    <div class="btn-group" style="margin-bottom: 20px;">
      <button id="invisible-trigger" class="btn btn-primary">{{ locale === 'zh-CN' ? '点击验证' : 'Click to Verify' }}</button>
    </div>

    <div v-if="result" class="result" :class="result.success ? 'success' : 'error'">
      {{ result.message }}
      <span v-if="result.riskScore !== undefined">({{ locale === 'zh-CN' ? '风险评分' : 'Risk Score' }}: {{ result.riskScore.toFixed(2) }})</span>
    </div>
  </section>
</template>
