// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Header from './components/Header.vue'
import Features from './components/Features.vue'
import TabNav from './components/TabNav.vue'
import Footer from './components/Footer.vue'

import SliderDemo from './pages/SliderDemo.vue'
import ClickDemo from './pages/ClickDemo.vue'
import PopupDemo from './pages/PopupDemo.vue'
import BackendDemo from './pages/BackendDemo.vue'
import InvisibleDemo from './pages/InvisibleDemo.vue'
import CustomImageDemo from './pages/CustomImageDemo.vue'
import AccessibilityDemo from './pages/AccessibilityDemo.vue'
import LocaleDemo from './pages/LocaleDemo.vue'
import StatisticsDemo from './pages/StatisticsDemo.vue'
import OptionsDemo from './pages/OptionsDemo.vue'
import ErrorDemo from './pages/ErrorDemo.vue'
import DarkModeDemo from './pages/DarkModeDemo.vue'

import '@captcha-pro/vue/style.css'
import './styles/global.css'

const activeTab = ref('slider')

onMounted(() => {
  const saved = localStorage.getItem('cp-theme')
  if (saved === 'dark' || (saved === null && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('cp-dark')
  }
})
</script>

<template>
  <div class="container">
    <Header />
    <Features />

    <TabNav v-model:active-tab="activeTab" />

    <SliderDemo v-show="activeTab === 'slider'" />
    <ClickDemo v-show="activeTab === 'click'" />
    <PopupDemo v-show="activeTab === 'popup'" />
    <BackendDemo v-show="activeTab === 'backend'" />
    <InvisibleDemo v-show="activeTab === 'invisible'" />
    <CustomImageDemo v-show="activeTab === 'custom'" />
    <AccessibilityDemo v-show="activeTab === 'accessibility'" />
    <LocaleDemo v-show="activeTab === 'locale'" />
    <StatisticsDemo v-show="activeTab === 'statistics'" />
    <OptionsDemo v-show="activeTab === 'options'" />
    <ErrorDemo v-show="activeTab === 'error'" />
    <DarkModeDemo v-show="activeTab === 'dark'" />

    <Footer />
  </div>
</template>

// examples/react/src/App.tsx
import type { ReactElement } from 'react'
import { useEffect, useState } from 'react'
import { Features } from './components/Features'
import { Footer } from './components/Footer'
import { Header } from './components/Header'
import { TabNav } from './components/TabNav'

import { LocaleProvider } from './hooks/useLocale'
import AccessibilityDemo from './pages/AccessibilityDemo'
import { BackendDemo } from './pages/BackendDemo'
import { ClickDemo } from './pages/ClickDemo'
import { CustomImageDemo } from './pages/CustomImageDemo'
import { DarkModeDemo } from './pages/DarkModeDemo'

import ErrorDemo from './pages/ErrorDemo'
import { InvisibleDemo } from './pages/InvisibleDemo'
import LocaleDemo from './pages/LocaleDemo'
import OptionsDemo from './pages/OptionsDemo'
import { PopupDemo } from './pages/PopupDemo'
import { SliderDemo } from './pages/SliderDemo'
import StatisticsDemo from './pages/StatisticsDemo'

import './styles/global.css'

type TabType = 'slider' | 'click' | 'popup' | 'backend' | 'invisible' | 'custom' | 'accessibility' | 'locale' | 'statistics' | 'options' | 'error' | 'dark'

export default function App(): ReactElement {
  const [activeTab, setActiveTab] = useState<TabType>('slider')

  useEffect(() => {
    const saved = localStorage.getItem('cp-theme')
    if (saved === 'dark' || (saved === null && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('cp-dark')
    }
  }, [])

  return (
    <LocaleProvider>
      <div className="container">
        <Header />
        <Features />
        <TabNav activeTab={activeTab} onTabChange={setActiveTab} />

        {activeTab === 'slider' && <SliderDemo />}
        {activeTab === 'click' && <ClickDemo />}
        {activeTab === 'popup' && <PopupDemo />}
        {activeTab === 'backend' && <BackendDemo />}
        {activeTab === 'invisible' && <InvisibleDemo />}
        {activeTab === 'custom' && <CustomImageDemo />}
        {activeTab === 'accessibility' && <AccessibilityDemo />}
        {activeTab === 'locale' && <LocaleDemo />}
        {activeTab === 'statistics' && <StatisticsDemo />}
      {activeTab === 'options' && <OptionsDemo />}
      {activeTab === 'error' && <ErrorDemo />}
      {activeTab === 'dark' && <DarkModeDemo />}

      <Footer />
      </div>
    </LocaleProvider>
  )
}
