// packages/vue2/src/components/ClickCaptcha.vue
<script>
import { ClickCaptcha, t } from '@captcha-pro/core'

export default {
  name: 'ClickCaptcha',

  props: {
    width: { type: Number, default: 300 },
    height: { type: Number, default: 170 },
    bgImage: { type: String, default: undefined },
    count: { type: Number, default: 3 },
    showRefresh: { type: Boolean, default: true },
    verifyMode: { type: String, default: 'frontend' },
    locale: { type: String, default: 'zh-CN' },
    secretKey: { type: String, default: undefined },
    backendVerify: { type: Object, default: undefined },
  },

  data() {
    return {
      captchaInstance: null,
    }
  },

  mounted() {
    this.initCaptcha()
  },

  beforeDestroy() {
    this.destroy()
  },

  methods: {
    initCaptcha() {
      if (!this.$refs.containerRef) return

      const options = {
        el: this.$refs.containerRef,
        width: this.width,
        height: this.height,
        bgImage: this.bgImage,
        count: this.count,
        showRefresh: this.showRefresh,
        verifyMode: this.verifyMode,
        locale: this.locale,
        security: this.secretKey ? { secretKey: this.secretKey } : undefined,
        backendVerify: this.backendVerify,
        onSuccess: () => {
          this.$emit('success')
        },
        onFail: () => {
          this.$emit('fail')
        },
        onRefresh: () => {
          this.$emit('refresh')
        },
      }

      this.captchaInstance = new ClickCaptcha(options)
      this.$emit('ready', this.captchaInstance)
    },

    refresh() {
      this.captchaInstance?.refresh()
    },

    getData() {
      return this.captchaInstance?.getData()
    },

    getStatistics() {
      return this.captchaInstance?.getStatistics()
    },

    getInstance() {
      return this.captchaInstance
    },

    destroy() {
      this.captchaInstance?.destroy()
      this.captchaInstance = null
    },
  },

  watch: {
    bgImage() {
      this.refresh()
    },
  },

  computed: {
    captchaAriaLabel() {
      return t('click.prompt', this.locale)
    },
  },
}
</script>

<template>
  <div class="captcha-vue2-wrapper" role="region" :aria-label="captchaAriaLabel">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue2-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/ClickCaptcha.tsx
import {
  type BackendVerifyOptions,
  type CaptchaData,
  type CaptchaStatistics,
  ClickCaptcha as ClickCaptchaCore,
  type ClickCaptchaInstance,
  type ClickCaptchaOptions,
  t,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface ClickCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  count?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: ClickCaptchaInstance) => void
  className?: string
}

export interface ClickCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => ClickCaptchaInstance | null
}

export const ClickCaptcha = React.forwardRef<ClickCaptchaRef, ClickCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      count = 3,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<ClickCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: ClickCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        count,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new ClickCaptchaCore(options) as ClickCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, count, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`} role="region" aria-label={t('click.prompt', locale)}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

ClickCaptcha.displayName = 'ClickCaptcha'
