// packages/vue3/src/components/ClickCaptcha.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import {
  ClickCaptcha as ClickCaptchaCore,
  type ClickCaptchaOptions,
  type ClickCaptchaInstance,
  type CaptchaData,
  type CaptchaStatistics,
  type BackendVerifyOptions,
} from '@captcha/core'

export interface Props {
  width?: number
  height?: number
  bgImage?: string
  count?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
}

const props = withDefaults(defineProps<Props>(), {
  width: 300,
  height: 170,
  count: 3,
  showRefresh: true,
  verifyMode: 'frontend',
})

const emit = defineEmits<{
  success: []
  fail: []
  refresh: []
  ready: [instance: ClickCaptchaInstance]
}>()

const containerRef = ref<HTMLElement | null>(null)
const captchaInstance = ref<ClickCaptchaInstance | null>(null)

const initCaptcha = () => {
  if (!containerRef.value) return

  const options: ClickCaptchaOptions = {
    el: containerRef.value,
    width: props.width,
    height: props.height,
    bgImage: props.bgImage,
    count: props.count,
    showRefresh: props.showRefresh,
    verifyMode: props.verifyMode,
    locale: props.locale,
    security: props.secretKey ? { secretKey: props.secretKey } : undefined,
    backendVerify: props.backendVerify,
    onSuccess: () => {
      emit('success')
    },
    onFail: () => {
      emit('fail')
    },
    onRefresh: () => {
      emit('refresh')
    },
  }

  captchaInstance.value = new ClickCaptchaCore(options) as ClickCaptchaInstance
  emit('ready', captchaInstance.value)
}

const refresh = () => {
  captchaInstance.value?.refresh()
}

const getData = (): CaptchaData => {
  return captchaInstance.value?.getData() as CaptchaData
}

const getStatistics = (): CaptchaStatistics => {
  return captchaInstance.value?.getStatistics() as CaptchaStatistics
}

const destroy = () => {
  captchaInstance.value?.destroy()
  captchaInstance.value = null
}

watch(
  () => props.bgImage,
  () => {
    refresh()
  }
)

onMounted(() => {
  initCaptcha()
})

onUnmounted(() => {
  destroy()
})

defineExpose({
  refresh,
  getData,
  getStatistics,
  getInstance: () => captchaInstance.value,
})
</script>

<template>
  <div class="captcha-vue3-wrapper">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue3-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/ClickCaptcha.tsx
import {
  type CaptchaData,
  type CaptchaStatistics,
  ClickCaptcha as ClickCaptchaCore,
  type ClickCaptchaInstance,
  type ClickCaptchaOptions,
  type BackendVerifyOptions,
} from '@captcha/core'
import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'

export interface ClickCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  count?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: ClickCaptchaInstance) => void
  className?: string
}

export interface ClickCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => ClickCaptchaInstance | null
}

export const ClickCaptcha = forwardRef<ClickCaptchaRef, ClickCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      count = 3,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<ClickCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: ClickCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        count,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new ClickCaptchaCore(options) as ClickCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, count, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

ClickCaptcha.displayName = 'ClickCaptcha'
