// packages/vue/src/components/ClickCaptcha.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import {
  type ClickCaptchaInstance,
  type BackendVerifyOptions,
  t,
} from '@captcha-pro/core'
import { useClickCaptcha, type UseClickCaptchaOptions } from '../composables/useClickCaptcha'

export interface Props {
  width?: number
  height?: number
  bgImage?: string
  count?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
}

const props = withDefaults(defineProps<Props>(), {
  width: 300,
  height: 170,
  count: 3,
  showRefresh: true,
  verifyMode: 'frontend',
})

const emit = defineEmits<{
  success: []
  fail: []
  refresh: []
  ready: [instance: ClickCaptchaInstance]
}>()

const containerRef = ref<HTMLElement | null>(null)

const { instance, isReady, refresh, getData, getStatistics, destroy } = useClickCaptcha({
  el: () => containerRef.value ?? undefined,
  width: props.width,
  height: props.height,
  bgImage: props.bgImage,
  count: props.count,
  showRefresh: props.showRefresh,
  verifyMode: props.verifyMode,
  locale: props.locale,
  secretKey: props.secretKey,
  backendVerify: props.backendVerify,
  onSuccess: () => emit('success'),
  onFail: () => emit('fail'),
  onRefresh: () => emit('refresh'),
})

watch(isReady, (ready) => {
  if (ready && instance.value) {
    emit('ready', instance.value)
  }
})

defineExpose({
  refresh,
  getData,
  getStatistics,
  getInstance: () => instance.value,
})
</script>

<template>
  <div class="captcha-vue-wrapper" role="region" :aria-label="t('click.prompt', props.locale)">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/ClickCaptcha.tsx
import {
  type BackendVerifyOptions,
  type CaptchaData,
  type CaptchaStatistics,
  ClickCaptcha as ClickCaptchaCore,
  type ClickCaptchaInstance,
  type ClickCaptchaOptions,
  t,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface ClickCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  count?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: ClickCaptchaInstance) => void
  className?: string
}

export interface ClickCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => ClickCaptchaInstance | null
}

export const ClickCaptcha = React.forwardRef<ClickCaptchaRef, ClickCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      count = 3,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<ClickCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: ClickCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        count,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new ClickCaptchaCore(options) as ClickCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, count, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`} role="region" aria-label={t('click.prompt', locale)}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

ClickCaptcha.displayName = 'ClickCaptcha'
