// packages/vue2/src/components/PopupCaptcha.vue
<script>
import { PopupCaptcha } from '@captcha-pro/core'

export default {
  name: 'PopupCaptcha',

  props: {
    type: { type: String, default: 'slider' },
    trigger: { type: String, default: undefined },
    modal: { type: Object, default: undefined },
    autoClose: { type: Boolean, default: true },
    closeDelay: { type: Number, default: 500 },
    captchaOptions: { type: Object, default: undefined },
  },

  data() {
    return {
      popupInstance: null,
    }
  },

  mounted() {
    this.initPopup()
  },

  beforeDestroy() {
    this.destroy()
  },

  methods: {
    initPopup() {
      const options = {
        type: this.type,
        trigger: this.trigger,
        modal: this.modal,
        autoClose: this.autoClose,
        closeDelay: this.closeDelay,
        captchaOptions: this.captchaOptions,
        onOpen: () => this.$emit('open'),
        onClose: () => this.$emit('close'),
        onSuccess: () => this.$emit('success'),
        onFail: () => this.$emit('fail'),
      }

      this.popupInstance = new PopupCaptcha(options)
      this.$emit('ready', this.popupInstance)
    },

    show() {
      this.popupInstance?.show()
    },

    hide() {
      this.popupInstance?.hide()
    },

    isVisible() {
      return this.popupInstance?.isVisible() ?? false
    },

    getInstance() {
      return this.popupInstance
    },

    destroy() {
      this.popupInstance?.destroy()
      this.popupInstance = null
    },
  },
}
</script>

<template>
  <div class="captcha-popup-wrapper">
    <slot />
  </div>
</template>

<style scoped>
.captcha-popup-wrapper {
  display: inline-block;
}
</style>

// packages/react/src/components/PopupCaptcha.tsx
import {
  PopupCaptcha as PopupCaptchaCore,
  type PopupCaptchaInstance,
  type PopupCaptchaOptions,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface PopupCaptchaProps {
  type?: 'slider' | 'click'
  trigger?: string
  children?: React.ReactNode
  modal?: {
    maskClosable?: boolean
    escClosable?: boolean
    showClose?: boolean
    title?: string
  }
  autoClose?: boolean
  closeDelay?: number
  captchaOptions?: Record<string, unknown>
  onOpen?: () => void
  onClose?: () => void
  onSuccess?: () => void
  onFail?: () => void
  onReady?: (instance: PopupCaptchaInstance) => void
}

export interface PopupCaptchaRef {
  show: () => void
  hide: () => void
  isVisible: () => boolean
  getInstance: () => PopupCaptchaInstance | null
}

export const PopupCaptcha = React.forwardRef<PopupCaptchaRef, PopupCaptchaProps>(
  (props, ref) => {
    const {
      type = 'slider',
      trigger,
      modal,
      autoClose = true,
      closeDelay = 500,
      captchaOptions,
      onOpen,
      onClose,
      onSuccess,
      onFail,
      onReady,
    } = props

    const popupInstance = useRef<PopupCaptchaInstance | null>(null)

    useEffect(() => {
      const options: PopupCaptchaOptions = {
        type,
        trigger,
        modal,
        autoClose,
        closeDelay,
        captchaOptions: captchaOptions as any,
        onOpen,
        onClose,
        onSuccess,
        onFail,
      }

      popupInstance.current = new PopupCaptchaCore(options) as PopupCaptchaInstance
      onReady?.(popupInstance.current)

      return () => {
        popupInstance.current?.destroy()
        popupInstance.current = null
      }
    }, [])

    useImperativeHandle(ref, () => ({
      show: () => popupInstance.current?.show(),
      hide: () => popupInstance.current?.hide(),
      isVisible: () => popupInstance.current?.isVisible() ?? false,
      getInstance: () => popupInstance.current,
    }))

    return <>{props.children}</>
  }
)

PopupCaptcha.displayName = 'PopupCaptcha'
