// packages/vue2/src/components/SliderCaptcha.vue
<script>
import { SliderCaptcha, t } from '@captcha-pro/core'

export default {
  name: 'SliderCaptcha',

  props: {
    width: { type: Number, default: 300 },
    height: { type: Number, default: 170 },
    bgImage: { type: String, default: undefined },
    sliderImage: { type: String, default: undefined },
    sliderWidth: { type: Number, default: 42 },
    sliderHeight: { type: Number, default: 42 },
    precision: { type: Number, default: 5 },
    showRefresh: { type: Boolean, default: true },
    verifyMode: { type: String, default: 'frontend' },
    locale: { type: String, default: 'zh-CN' },
    secretKey: { type: String, default: undefined },
    backendVerify: { type: Object, default: undefined },
  },

  data() {
    return {
      captchaInstance: null,
    }
  },

  mounted() {
    this.initCaptcha()
  },

  beforeDestroy() {
    this.destroy()
  },

  methods: {
    initCaptcha() {
      if (!this.$refs.containerRef) return

      const options = {
        el: this.$refs.containerRef,
        width: this.width,
        height: this.height,
        bgImage: this.bgImage,
        sliderImage: this.sliderImage,
        sliderWidth: this.sliderWidth,
        sliderHeight: this.sliderHeight,
        precision: this.precision,
        showRefresh: this.showRefresh,
        verifyMode: this.verifyMode,
        locale: this.locale,
        security: this.secretKey ? { secretKey: this.secretKey } : undefined,
        backendVerify: this.backendVerify,
        onSuccess: () => {
          this.$emit('success')
        },
        onFail: () => {
          this.$emit('fail')
        },
        onRefresh: () => {
          this.$emit('refresh')
        },
      }

      this.captchaInstance = new SliderCaptcha(options)
      this.$emit('ready', this.captchaInstance)
    },

    refresh() {
      this.captchaInstance?.refresh()
    },

    getData() {
      return this.captchaInstance?.getData()
    },

    getStatistics() {
      return this.captchaInstance?.getStatistics()
    },

    getInstance() {
      return this.captchaInstance
    },

    destroy() {
      this.captchaInstance?.destroy()
      this.captchaInstance = null
    },
  },

  watch: {
    bgImage() {
      this.refresh()
    },
    sliderImage() {
      this.refresh()
    },
  },

  computed: {
    captchaAriaLabel() {
      return t('slider.slide', this.locale)
    },
  },
}
</script>

<template>
  <div class="captcha-vue2-wrapper" role="region" :aria-label="captchaAriaLabel">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue2-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/SliderCaptcha.tsx
import {
  type BackendVerifyOptions,
  type CaptchaData,
  type CaptchaStatistics,
  SliderCaptcha as SliderCaptchaCore,
  type SliderCaptchaInstance,
  type SliderCaptchaOptions,
  t,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface SliderCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  sliderImage?: string
  sliderWidth?: number
  sliderHeight?: number
  precision?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: SliderCaptchaInstance) => void
  className?: string
}

export interface SliderCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => SliderCaptchaInstance | null
}

export const SliderCaptcha = React.forwardRef<SliderCaptchaRef, SliderCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      sliderImage,
      sliderWidth = 42,
      sliderHeight = 42,
      precision = 5,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<SliderCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: SliderCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        sliderImage,
        sliderWidth,
        sliderHeight,
        precision,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new SliderCaptchaCore(options) as SliderCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, sliderImage, sliderWidth, sliderHeight, precision, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`} role="region" aria-label={t('slider.slide', locale)}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

SliderCaptcha.displayName = 'SliderCaptcha'
