// packages/vue/src/components/SliderCaptcha.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import {
  type SliderCaptchaInstance,
  type BackendVerifyOptions,
  t,
} from '@captcha-pro/core'
import { useSliderCaptcha, type UseSliderCaptchaOptions } from '../composables/useSliderCaptcha'

export interface Props {
  width?: number
  height?: number
  bgImage?: string
  sliderImage?: string
  sliderWidth?: number
  sliderHeight?: number
  precision?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
}

const props = withDefaults(defineProps<Props>(), {
  width: 300,
  height: 170,
  sliderWidth: 42,
  sliderHeight: 42,
  precision: 5,
  showRefresh: true,
  verifyMode: 'frontend',
})

const emit = defineEmits<{
  success: []
  fail: []
  refresh: []
  ready: [instance: SliderCaptchaInstance]
}>()

const containerRef = ref<HTMLElement | null>(null)

const { instance, isReady, refresh, getData, getStatistics, destroy } = useSliderCaptcha({
  el: () => containerRef.value ?? undefined,
  width: props.width,
  height: props.height,
  bgImage: props.bgImage,
  sliderImage: props.sliderImage,
  sliderWidth: props.sliderWidth,
  sliderHeight: props.sliderHeight,
  precision: props.precision,
  showRefresh: props.showRefresh,
  verifyMode: props.verifyMode,
  locale: props.locale,
  secretKey: props.secretKey,
  backendVerify: props.backendVerify,
  onSuccess: () => emit('success'),
  onFail: () => emit('fail'),
  onRefresh: () => emit('refresh'),
})

watch(isReady, (ready) => {
  if (ready && instance.value) {
    emit('ready', instance.value)
  }
})

defineExpose({
  refresh,
  getData,
  getStatistics,
  getInstance: () => instance.value,
})
</script>

<template>
  <div class="captcha-vue-wrapper" role="region" :aria-label="t('slider.slide', props.locale)">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/SliderCaptcha.tsx
import {
  type BackendVerifyOptions,
  type CaptchaData,
  type CaptchaStatistics,
  SliderCaptcha as SliderCaptchaCore,
  type SliderCaptchaInstance,
  type SliderCaptchaOptions,
  t,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface SliderCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  sliderImage?: string
  sliderWidth?: number
  sliderHeight?: number
  precision?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: SliderCaptchaInstance) => void
  className?: string
}

export interface SliderCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => SliderCaptchaInstance | null
}

export const SliderCaptcha = React.forwardRef<SliderCaptchaRef, SliderCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      sliderImage,
      sliderWidth = 42,
      sliderHeight = 42,
      precision = 5,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<SliderCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: SliderCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        sliderImage,
        sliderWidth,
        sliderHeight,
        precision,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new SliderCaptchaCore(options) as SliderCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, sliderImage, sliderWidth, sliderHeight, precision, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`} role="region" aria-label={t('slider.slide', locale)}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

SliderCaptcha.displayName = 'SliderCaptcha'
