// packages/vue3/src/components/SliderCaptcha.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import {
  SliderCaptcha as SliderCaptchaCore,
  type SliderCaptchaOptions,
  type SliderCaptchaInstance,
  type CaptchaData,
  type CaptchaStatistics,
  type BackendVerifyOptions,
} from '@captcha/core'

export interface Props {
  width?: number
  height?: number
  bgImage?: string
  sliderImage?: string
  sliderWidth?: number
  sliderHeight?: number
  precision?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
}

const props = withDefaults(defineProps<Props>(), {
  width: 300,
  height: 170,
  sliderWidth: 42,
  sliderHeight: 42,
  precision: 5,
  showRefresh: true,
  verifyMode: 'frontend',
})

const emit = defineEmits<{
  success: []
  fail: []
  refresh: []
  ready: [instance: SliderCaptchaInstance]
}>()

const containerRef = ref<HTMLElement | null>(null)
const captchaInstance = ref<SliderCaptchaInstance | null>(null)

const initCaptcha = () => {
  if (!containerRef.value) return

  const options: SliderCaptchaOptions = {
    el: containerRef.value,
    width: props.width,
    height: props.height,
    bgImage: props.bgImage,
    sliderImage: props.sliderImage,
    sliderWidth: props.sliderWidth,
    sliderHeight: props.sliderHeight,
    precision: props.precision,
    showRefresh: props.showRefresh,
    verifyMode: props.verifyMode,
    locale: props.locale,
    security: props.secretKey ? { secretKey: props.secretKey } : undefined,
    backendVerify: props.backendVerify,
    onSuccess: () => {
      emit('success')
    },
    onFail: () => {
      emit('fail')
    },
    onRefresh: () => {
      emit('refresh')
    },
  }

  captchaInstance.value = new SliderCaptchaCore(options) as SliderCaptchaInstance
  emit('ready', captchaInstance.value)
}

const refresh = () => {
  captchaInstance.value?.refresh()
}

const getData = (): CaptchaData => {
  return captchaInstance.value?.getData() as CaptchaData
}

const getStatistics = (): CaptchaStatistics => {
  return captchaInstance.value?.getStatistics() as CaptchaStatistics
}

const destroy = () => {
  captchaInstance.value?.destroy()
  captchaInstance.value = null
}

watch(
  () => [props.bgImage, props.sliderImage],
  () => {
    refresh()
  }
)

onMounted(() => {
  initCaptcha()
})

onUnmounted(() => {
  destroy()
})

defineExpose({
  refresh,
  getData,
  getStatistics,
  getInstance: () => captchaInstance.value,
})
</script>

<template>
  <div class="captcha-vue3-wrapper">
    <div ref="containerRef" class="captcha-container" />
  </div>
</template>

<style scoped>
.captcha-vue3-wrapper {
  position: relative;
  display: inline-block;
}

.captcha-container {
  position: relative;
}
</style>

// packages/react/src/components/SliderCaptcha.tsx
import {
  type CaptchaData,
  type CaptchaStatistics,
  SliderCaptcha as SliderCaptchaCore,
  type SliderCaptchaInstance,
  type SliderCaptchaOptions,
  type BackendVerifyOptions,
} from '@captcha/core'
import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'

export interface SliderCaptchaProps {
  width?: number
  height?: number
  bgImage?: string
  sliderImage?: string
  sliderWidth?: number
  sliderHeight?: number
  precision?: number
  showRefresh?: boolean
  verifyMode?: 'frontend' | 'backend'
  locale?: 'zh-CN' | 'en-US'
  secretKey?: string
  backendVerify?: BackendVerifyOptions
  onSuccess?: () => void
  onFail?: () => void
  onRefresh?: () => void
  onReady?: (instance: SliderCaptchaInstance) => void
  className?: string
}

export interface SliderCaptchaRef {
  refresh: () => void
  getData: () => CaptchaData
  getStatistics: () => CaptchaStatistics
  getInstance: () => SliderCaptchaInstance | null
}

export const SliderCaptcha = forwardRef<SliderCaptchaRef, SliderCaptchaProps>(
  (props, ref) => {
    const {
      width = 300,
      height = 170,
      bgImage,
      sliderImage,
      sliderWidth = 42,
      sliderHeight = 42,
      precision = 5,
      showRefresh = true,
      verifyMode = 'frontend',
      locale = 'zh-CN',
      secretKey,
      backendVerify,
      onSuccess,
      onFail,
      onRefresh,
      onReady,
      className,
    } = props

    const containerRef = useRef<HTMLDivElement>(null)
    const captchaInstance = useRef<SliderCaptchaInstance | null>(null)

    useEffect(() => {
      if (!containerRef.current) return

      const options: SliderCaptchaOptions = {
        el: containerRef.current,
        width,
        height,
        bgImage,
        sliderImage,
        sliderWidth,
        sliderHeight,
        precision,
        showRefresh,
        verifyMode,
        locale,
        security: secretKey ? { secretKey } : undefined,
        backendVerify,
        onSuccess,
        onFail,
        onRefresh,
      }

      captchaInstance.current = new SliderCaptchaCore(options) as SliderCaptchaInstance
      onReady?.(captchaInstance.current)

      return () => {
        captchaInstance.current?.destroy()
        captchaInstance.current = null
      }
    }, [width, height, bgImage, sliderImage, sliderWidth, sliderHeight, precision, showRefresh, verifyMode, locale, secretKey, backendVerify, onSuccess, onFail, onRefresh, onReady])

    useImperativeHandle(ref, () => ({
      refresh: () => captchaInstance.current?.refresh(),
      getData: () => captchaInstance.current?.getData() as CaptchaData,
      getStatistics: () => captchaInstance.current?.getStatistics() as CaptchaStatistics,
      getInstance: () => captchaInstance.current,
    }))

    return (
      <div className={`captcha-react-wrapper ${className || ''}`}>
        <div ref={containerRef} className="captcha-container" />
      </div>
    )
  }
)

SliderCaptcha.displayName = 'SliderCaptcha'
