// packages/react/src/components/PopupCaptcha.tsx
import {
  PopupCaptcha as PopupCaptchaCore,
  type PopupCaptchaInstance,
  type PopupCaptchaOptions,
} from '@captcha-pro/core'
import * as React from 'react'
import { useEffect, useImperativeHandle, useRef } from 'react'

export interface PopupCaptchaProps {
  type?: 'slider' | 'click'
  trigger?: string
  children?: React.ReactNode
  modal?: {
    maskClosable?: boolean
    escClosable?: boolean
    showClose?: boolean
    title?: string
  }
  autoClose?: boolean
  closeDelay?: number
  captchaOptions?: Record<string, unknown>
  onOpen?: () => void
  onClose?: () => void
  onSuccess?: () => void
  onFail?: () => void
  onReady?: (instance: PopupCaptchaInstance) => void
}

export interface PopupCaptchaRef {
  show: () => void
  hide: () => void
  isVisible: () => boolean
  getInstance: () => PopupCaptchaInstance | null
}

export const PopupCaptcha = React.forwardRef<PopupCaptchaRef, PopupCaptchaProps>(
  (props, ref) => {
    const {
      type = 'slider',
      trigger,
      modal,
      autoClose = true,
      closeDelay = 500,
      captchaOptions,
      onOpen,
      onClose,
      onSuccess,
      onFail,
      onReady,
    } = props

    const popupInstance = useRef<PopupCaptchaInstance | null>(null)

    useEffect(() => {
      const options: PopupCaptchaOptions = {
        type,
        trigger,
        modal,
        autoClose,
        closeDelay,
        captchaOptions: captchaOptions as any,
        onOpen,
        onClose,
        onSuccess,
        onFail,
      }

      popupInstance.current = new PopupCaptchaCore(options) as PopupCaptchaInstance
      onReady?.(popupInstance.current)

      return () => {
        popupInstance.current?.destroy()
        popupInstance.current = null
      }
    }, [])

    useImperativeHandle(ref, () => ({
      show: () => popupInstance.current?.show(),
      hide: () => popupInstance.current?.hide(),
      isVisible: () => popupInstance.current?.isVisible() ?? false,
      getInstance: () => popupInstance.current,
    }))

    return <>{props.children}</>
  }
)

PopupCaptcha.displayName = 'PopupCaptcha'

// packages/vue3/src/components/PopupCaptcha.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import {
  PopupCaptcha as PopupCaptchaCore,
  type PopupCaptchaOptions,
  type PopupCaptchaInstance,
} from '@captcha-pro/core'

export interface Props {
  type?: 'slider' | 'click'
  trigger?: string
  modal?: {
    maskClosable?: boolean
    escClosable?: boolean
    showClose?: boolean
    title?: string
  }
  autoClose?: boolean
  closeDelay?: number
  captchaOptions?: Record<string, unknown>
}

const props = withDefaults(defineProps<Props>(), {
  type: 'slider',
  autoClose: true,
  closeDelay: 500,
})

const emit = defineEmits<{
  open: []
  close: []
  success: []
  fail: []
  ready: [instance: PopupCaptchaInstance]
}>()

const popupInstance = ref<PopupCaptchaInstance | null>(null)

const initPopup = () => {
  const options: PopupCaptchaOptions = {
    type: props.type,
    trigger: props.trigger,
    modal: props.modal,
    autoClose: props.autoClose,
    closeDelay: props.closeDelay,
    captchaOptions: props.captchaOptions as any,
    onOpen: () => emit('open'),
    onClose: () => emit('close'),
    onSuccess: () => emit('success'),
    onFail: () => emit('fail'),
  }

  popupInstance.value = new PopupCaptchaCore(options) as PopupCaptchaInstance
  emit('ready', popupInstance.value)
}

const show = () => {
  popupInstance.value?.show()
}

const hide = () => {
  popupInstance.value?.hide()
}

const isVisible = () => {
  return popupInstance.value?.isVisible() ?? false
}

const destroy = () => {
  popupInstance.value?.destroy()
  popupInstance.value = null
}

onMounted(() => {
  initPopup()
})

onUnmounted(() => {
  destroy()
})

defineExpose({
  show,
  hide,
  isVisible,
  getInstance: () => popupInstance.value,
})
</script>

<template>
  <slot />
</template>
