// examples/vue/src/components/Features.vue
<script setup lang="ts">
import { useLocale } from '../composables/useLocale'

const { currentLocale, t } = useLocale()
</script>

<template>
  <section class="features">
    <h2>{{ currentLocale === 'zh-CN' ? '功能特性' : 'Features' }}</h2>
    <div class="feature-grid">
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '随机滑块形状' : 'Random slider shapes' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '迷惑坑位防机器人' : 'Decoy holes anti-bot' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '渐变背景装饰' : 'Gradient background' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '中文词汇库' : 'Chinese vocabulary' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '弹窗模式' : 'Popup mode' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '后端验证' : 'Backend verify' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '智能无感验证' : 'Invisible captcha' }}</div>
      <div class="feature-item">✓ {{ currentLocale === 'zh-CN' ? '多语言支持' : 'i18n support' }}</div>
      <div class="feature-item">
        ✓ {{ currentLocale === 'zh-CN' ? '系统暗色模式' : 'System dark mode' }}
        <span class="new-badge">v2.3.0</span>
      </div>
      <div class="feature-item">
        ✓ {{ currentLocale === 'zh-CN' ? '弹窗焦点陷阱' : 'Popup focus trap' }}
        <span class="new-badge">v2.3.0</span>
      </div>
      <div class="feature-item">
        ✓ {{ currentLocale === 'zh-CN' ? '无障碍(a11y)' : 'Accessibility (a11y)' }}
        <span class="new-badge">v2.2.0</span>
      </div>
      <div class="feature-item">
        ✓ {{ currentLocale === 'zh-CN' ? 'Native 三端对齐' : 'Native alignment' }}
        <span class="new-badge">v2.1.0</span>
      </div>
    </div>
  </section>
</template>

// examples/react/src/components/Features.tsx
import type { ReactElement } from 'react'
import { useLocale } from '../hooks/useLocale'

export function Features(): ReactElement {
  const { currentLocale, t } = useLocale()

  const features = [
    { zh: '随机滑块形状', en: 'Random slider shapes' },
    { zh: '迷惑坑位防机器人', en: 'Decoy holes anti-bot' },
    { zh: '渐变背景装饰', en: 'Gradient background' },
    { zh: '中文词汇库', en: 'Chinese vocabulary' },
    { zh: '弹窗模式', en: 'Popup mode' },
    { zh: '后端验证', en: 'Backend verify' },
    { zh: '智能无感验证', en: 'Invisible captcha' },
    { zh: '多语言支持', en: 'i18n support' },
    { zh: '系统暗色模式', en: 'System dark mode', badge: 'v2.3.0' },
    { zh: '弹窗焦点陷阱', en: 'Popup focus trap', badge: 'v2.3.0' },
    { zh: '无障碍(a11y)', en: 'Accessibility (a11y)', badge: 'v2.2.0' },
    { zh: 'Native 三端对齐', en: 'Native alignment', badge: 'v2.1.0' },
  ]

  return (
    <section className="features">
      <h2>{t('功能特性', 'Features')}</h2>
      <div className="feature-grid">
        {features.map((f) => (
          <div key={f.en} className="feature-item">
            ✓
            {currentLocale === 'zh-CN' ? f.zh : f.en}
            {f.badge && <span className="new-badge">{f.badge}</span>}
          </div>
        ))}
      </div>
    </section>
  )
}
