// packages/taro-react/src/components/SliderCaptcha.tsx
import type { SliderCaptchaProps, SliderCaptchaRef } from '../types'
import { DEFAULT_LOCALE, getLocaleMessage } from '@captcha-pro/mp-shared'
import { Image, MovableArea, MovableView, Text, View } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import { fetchCaptcha, verifyCaptcha } from '../request'
import '../styles/captcha.scss'

/** SliderCaptcha — backend-only mode */
const SliderCaptcha = forwardRef<SliderCaptchaRef, SliderCaptchaProps>(({
  width = 650,
  height = 380,
  sliderWidth = 80,
  sliderHeight = 80,
  showRefresh = true,
  backend,
  onSuccess,
  onFail,
  onRefresh,
  onError,
}, ref) => {
  const t = (key: string): string => getLocaleMessage(DEFAULT_LOCALE, key)

  // Backend data
  const [captchaId, setCaptchaId] = useState('')
  const [bgImage, setBgImage] = useState('')
  const [sliderImage, setSliderImage] = useState('')
  const [sliderY, setSliderY] = useState(0)

  // UI state
  const [sliderX, setSliderX] = useState(0)
  const [status, setStatus] = useState<'' | 'success' | 'fail'>('')
  const [loading, setLoading] = useState(true)
  const [errorMsg, setErrorMsg] = useState('')

  // Track loading to avoid race conditions
  const loadSeqRef = useRef(0)

  // Use refs for callbacks to avoid dependency issues
  const onSuccessRef = useRef(onSuccess)
  const onFailRef = useRef(onFail)
  const onRefreshRef = useRef(onRefresh)
  const onErrorRef = useRef(onError)

  // Update refs when props change
  useEffect(() => {
    onSuccessRef.current = onSuccess
    onFailRef.current = onFail
    onRefreshRef.current = onRefresh
    onErrorRef.current = onError
  }, [onSuccess, onFail, onRefresh, onError])

  // Convert rpx to px
  const rpxToPx = useCallback((rpx: number) => {
    return Math.floor(rpx * Taro.getWindowInfo().screenWidth / 750)
  }, [])

  // Container size in px (computed from rpx)
  const widthPx = useMemo(() => rpxToPx(width), [width, rpxToPx])
  const heightPx = useMemo(() => rpxToPx(height), [height, rpxToPx])

  // Load captcha from backend
  const loadCaptcha = useCallback(async () => {
    const seq = ++loadSeqRef.current
    setLoading(true)
    setErrorMsg('')
    setStatus('')
    setSliderX(0)

    try {
      const res = await fetchCaptcha(backend, {
        type: 'slider',
        width: widthPx || rpxToPx(width),
        height: heightPx || rpxToPx(height),
        sliderWidth: rpxToPx(sliderWidth),
        sliderHeight: rpxToPx(sliderHeight),
      })

      // Skip if a newer load was triggered
      if (seq !== loadSeqRef.current) return

      if (!res.success || !res.data) {
        throw new Error(res.message || 'Failed to get captcha')
      }

      const { captchaId: id, bgImage: bg, sliderImage: slider, sliderY: y } = res.data
      setCaptchaId(id)
      setBgImage(bg)
      setSliderImage(slider ?? '')
      setSliderY(y ?? 0)
    } catch (err) {
      if (seq !== loadSeqRef.current) return
      const error = err instanceof Error ? err : new Error(String(err))
      setErrorMsg(error.message)
      onError?.(error)
    } finally {
      if (seq === loadSeqRef.current) {
        setLoading(false)
      }
    }
  }, [backend, widthPx, heightPx, width, height, sliderWidth, sliderHeight, rpxToPx, onError])

  // Load on mount
  useEffect(() => {
    if (widthPx && heightPx) {
      loadCaptcha()
    }
  }, [widthPx, heightPx])

  // Handle slider drag
  const handleSliderChange = useCallback((e: { detail: { x: number } }): void => {
    if (status || loading) return
    setSliderX(e.detail.x)
  }, [status, loading])

  // Handle slider release → verify
  const handleSliderEnd = useCallback(async (): Promise<void> => {
    if (status || loading || !captchaId) return

    setLoading(true)
    try {
      const res = await verifyCaptcha(backend, {
        captchaId,
        type: 'slider',
        target: [sliderX],
      })

      if (res.success) {
        setStatus('success')
        onSuccessRef.current?.(res.data)
      } else {
        setStatus('fail')
        onFailRef.current?.()
        // Auto refresh after failure
        setTimeout(() => {
          loadCaptcha()
          onRefreshRef.current?.()
        }, 800)
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      onError?.(error)
      setStatus('fail')
      setTimeout(() => loadCaptcha(), 800)
    } finally {
      setLoading(false)
    }
  }, [status, loading, captchaId, sliderX, backend, loadCaptcha, onSuccess, onError])

  // Manual refresh
  const refresh = useCallback(() => {
    loadCaptcha()
    onRefreshRef.current?.()
  }, [loadCaptcha])

  // Expose refresh method via ref
  useImperativeHandle(ref, () => ({ refresh }), [refresh])

  const actualSliderWidth = rpxToPx(sliderWidth)
  const actualSliderHeight = rpxToPx(sliderHeight)
  const sliderBarHeight = rpxToPx(80)

  return (
    <View class="captcha-container">
      {/* Captcha area */}
      <View
        class="captcha-area"
        role="region"
        aria-label={t('slider_hint')}
        style={{
          width: `${widthPx}px`,
          height: `${heightPx}px`,
          'border-radius': '16rpx',
        }}
      >
        {/* Background image from backend */}
        {bgImage ? (
          <Image
            src={bgImage}
            mode="aspectFill"
            class="bg-image"
            style={{ width: `${widthPx}px`, height: `${heightPx}px` }}
          />
        ) : (
          <View class="captcha-loading" style={{ width: `${widthPx}px`, height: `${heightPx}px` }}>
            <Text>{errorMsg || '加载中...'}</Text>
          </View>
        )}

        {/* Slider block overlay from backend */}
        {sliderImage && !loading && (
          <Image
            src={sliderImage}
            class="slider-block"
            style={{
              width: `${actualSliderWidth}px`,
              height: `${actualSliderHeight}px`,
              top: `${sliderY}px`,
              left: `${sliderX}px`,
            }}
          />
        )}

        {/* Refresh button */}
        {showRefresh && !loading && (
          <View class="refresh-btn" role="button" aria-label={t('refresh')} onClick={refresh}>
            <Text class="refresh-icon">⟳</Text>
          </View>
        )}

        {/* Status overlay */}
        {status && (
          <View class={`status-overlay ${status}`} aria-live="polite" aria-atomic="true">
            <View class="status-icon"><Text>{status === 'success' ? '✓' : '✕'}</Text></View>
            <Text class="status-text">{status === 'success' ? '验证成功' : '验证失败'}</Text>
          </View>
        )}
      </View>

      {/* Slider bar */}
      <View
        class="slider-bar"
        style={{ width: `${widthPx}px`, height: `${sliderBarHeight}px` }}
      >
        <View class="slider-track" />
        <View class="slider-hint">
          <Text>→ 按住滑块，拖动完成验证</Text>
        </View>
        <MovableArea
          class="slider-area"
          style={{ width: `${widthPx}px`, height: `${sliderBarHeight}px` }}
        >
          <MovableView
            class="slider-thumb"
            direction="horizontal"
            x={sliderX}
            damping={40}
            role="slider"
            aria-label={t('slider_hint')}
            aria-valuemin={0}
            aria-valuemax={widthPx - actualSliderWidth}
            aria-valuenow={sliderX}
            onChange={handleSliderChange}
            onTouchEnd={handleSliderEnd}
            style={{ width: `${actualSliderWidth}px`, height: `${sliderBarHeight}px` }}
          >
            <Text class="slider-arrow">→</Text>
          </MovableView>
        </MovableArea>
      </View>
    </View>
  )
})

SliderCaptcha.displayName = 'SliderCaptcha'

export default SliderCaptcha

// packages/uniapp-vue/src/components/slider-captcha.vue
<script setup lang="ts">
import { useSliderCaptcha } from '../composables/useSliderCaptcha'
import { DEFAULT_LOCALE, getLocaleMessage } from '@captcha-pro/mp-shared'
import '../styles/captcha.scss'

const props = defineProps({
	width: { type: Number, default: 650 },
	height: { type: Number, default: 380 },
	sliderWidth: { type: Number, default: 80 },
	sliderHeight: { type: Number, default: 80 },
	showRefresh: { type: Boolean, default: true },
	backend: { type: Object, required: true },
	onSuccess: { type: Function, default: undefined },
	onFail: { type: Function, default: undefined },
	onRefresh: { type: Function, default: undefined },
	onError: { type: Function, default: undefined },
})

const t = (key: string) => getLocaleMessage(DEFAULT_LOCALE, key)

const {
	bgImage,
	sliderImage,
	sliderY,
	sliderX,
	captchaId,
	status,
	loading,
	errorMsg,
	refresh,
	handleSliderChange,
	handleSliderEnd,
	rpxToPx,
	widthPx,
	heightPx,
} = useSliderCaptcha(props.backend as any, {
	width: props.width,
	height: props.height,
	sliderWidth: props.sliderWidth,
	sliderHeight: props.sliderHeight,
	onSuccess: props.onSuccess,
	onFail: props.onFail,
	onRefresh: props.onRefresh,
	onError: props.onError,
})

const actualSliderWidth = rpxToPx(props.sliderWidth)
const sliderBarHeight = rpxToPx(80)

defineExpose({ refresh })
</script>

<template>
  <view class="captcha-container">
    <view
      class="captcha-area"
      :style="{
        width: `${widthPx}px`,
        height: `${heightPx}px`,
        borderRadius: '16rpx',
      }"
      role="region"
      :aria-label="t('slider_hint')"
    >
      <image
        v-if="bgImage"
        :src="bgImage"
        mode="aspectFill"
        class="bg-image"
        :style="{ width: `${widthPx}px`, height: `${heightPx}px` }"
      />
      <view
        v-else
        class="captcha-loading"
        :style="{ width: `${widthPx}px`, height: `${heightPx}px` }"
      >
        <text>{{ errorMsg || '加载中...' }}</text>
      </view>

      <image
        v-if="sliderImage && !loading"
        :src="sliderImage"
        class="slider-block"
        :style="{
          width: `${rpxToPx(sliderWidth)}px`,
          height: `${rpxToPx(sliderHeight)}px`,
          top: `${sliderY}px`,
          left: `${sliderX}px`,
        }"
      />

      <view v-if="showRefresh && !loading" class="refresh-btn" role="button" :aria-label="t('refresh')" @tap="refresh">
        <text class="refresh-icon">⟳</text>
      </view>

      <view v-if="status" class="status-overlay" :class="status" aria-live="polite" aria-atomic="true">
        <view class="status-icon"><text>{{ status === 'success' ? '✓' : '✕' }}</text></view>
        <text class="status-text">{{ status === 'success' ? '验证成功' : '验证失败' }}</text>
      </view>
    </view>

    <view class="slider-bar" :style="{ width: `${widthPx}px`, height: `${sliderBarHeight}px` }">
      <view class="slider-track" />
      <view class="slider-hint"><text>→ 按住滑块，拖动完成验证</text></view>
      <movable-area
        class="slider-area"
        :style="{ width: `${widthPx}px`, height: `${sliderBarHeight}px` }"
      >
        <movable-view
          class="slider-thumb"
          direction="horizontal"
          :x="sliderX"
          :damping="40"
          role="slider"
          :aria-label="t('slider_hint')"
          :aria-valuemin="0"
          :aria-valuemax="widthPx - actualSliderWidth"
          :aria-valuenow="sliderX"
          @change="(e: any) => handleSliderChange(e.detail.x)"
          @touchend="handleSliderEnd"
          :style="{ width: `${actualSliderWidth}px`, height: `${sliderBarHeight}px` }"
        >
          <text class="slider-arrow">→</text>
        </movable-view>
      </movable-area>
    </view>
  </view>
</template>
