// examples/vue2/src/pages/SliderDemo.vue
<template>
  <section class="demo-section">
    <h2>🧩 {{ locale === 'zh-CN' ? '滑动拼图验证码' : 'Slider Captcha' }}</h2>

    <div class="options">
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '验证精度' : 'Precision' }}:</label>
        <select v-model.number="precision">
          <option :value="3">{{ locale === 'zh-CN' ? '高 (3px)' : 'High (3px)' }}</option>
          <option :value="5">{{ locale === 'zh-CN' ? '中 (5px)' : 'Medium (5px)' }}</option>
          <option :value="10">{{ locale === 'zh-CN' ? '低 (10px)' : 'Low (10px)' }}</option>
        </select>
      </div>
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '显示刷新' : 'Show Refresh' }}:</label>
        <input type="checkbox" v-model="showRefresh">
      </div>
    </div>

    <div class="captcha-box">
      <SliderCaptcha
        ref="captchaRef"
        :width="320"
        :height="180"
        :precision="precision"
        :show-refresh="showRefresh"
        :locale="locale"
        @success="onSuccess"
      />
    </div>

    <div class="btn-group">
      <button class="btn btn-primary" @click="reset">{{ locale === 'zh-CN' ? '重置验证码' : 'Reset' }}</button>
      <button class="btn btn-secondary" @click="getData">{{ locale === 'zh-CN' ? '获取数据' : 'Get Data' }}</button>
      <button class="btn btn-secondary" @click="updateStats">{{ locale === 'zh-CN' ? '查看统计' : 'Statistics' }}</button>
    </div>

    <div v-if="stats.totalAttempts" class="stats">
      <div class="stat-item">
        <span class="stat-value">{{ stats.totalAttempts }}</span>
        <span class="stat-label">{{ locale === 'zh-CN' ? '总尝试' : 'Attempts' }}</span>
      </div>
      <div class="stat-item">
        <span class="stat-value">{{ stats.successCount }}</span>
        <span class="stat-label">{{ locale === 'zh-CN' ? '成功' : 'Success' }}</span>
      </div>
      <div class="stat-item">
        <span class="stat-value">{{ stats.successRate }}%</span>
        <span class="stat-label">{{ locale === 'zh-CN' ? '成功率' : 'Rate' }}</span>
      </div>
      <div class="stat-item">
        <span class="stat-value">{{ stats.avgVerifyTime }}ms</span>
        <span class="stat-label">{{ locale === 'zh-CN' ? '平均耗时' : 'Avg Time' }}</span>
      </div>
    </div>
  </section>
</template>

<script>
import { SliderCaptcha } from '@captcha/vue2'

export default {
  name: 'SliderDemo',
  components: { SliderCaptcha },
  props: {
    locale: { type: String, default: 'zh-CN' }
  },
  data() {
    return {
      precision: 5,
      showRefresh: true,
      stats: {}
    }
  },
  methods: {
    onSuccess() {
      console.log('Slider success:', this.$refs.captchaRef?.getData())
      this.updateStats()
    },
    updateStats() {
      const stats = this.$refs.captchaRef?.getStatistics()
      if (stats) {
        this.stats = {
          totalAttempts: stats.totalAttempts,
          successCount: stats.successCount,
          successRate: stats.successRate,
          avgVerifyTime: stats.avgVerifyTime
        }
      }
    },
    reset() {
      this.$refs.captchaRef?.refresh()
    },
    getData() {
      const data = this.$refs.captchaRef?.getData()
      console.log('Slider data:', data)
      alert(this.locale === 'zh-CN' ? '验证数据已输出到控制台' : 'Data logged to console')
    }
  }
}
</script>

// examples/react/src/pages/SliderDemo.tsx
import { useState, useRef } from 'react'
import { SliderCaptcha, type SliderCaptchaInstance, type CaptchaStatistics } from '@captcha/react'
import { useLocale } from '../hooks/useLocale'

export function SliderDemo() {
  const { currentLocale, t } = useLocale()
  const [precision, setPrecision] = useState(5)
  const [stats, setStats] = useState<CaptchaStatistics | null>(null)
  const captchaRef = useRef<SliderCaptchaInstance>(null)

  const updateStats = () => {
    const s = captchaRef.current?.getStatistics()
    if (s) setStats(s)
  }

  return (
    <section className="demo-section">
      <h2>🧩 {t('滑动拼图验证码', 'Slider Captcha')}</h2>

      <div className="options">
        <div className="option-row">
          <label>{t('验证精度', 'Precision')}:</label>
          <select value={precision} onChange={(e) => setPrecision(Number(e.target.value))}>
            <option value={3}>{t('高 (3px)', 'High (3px)')}</option>
            <option value={5}>{t('中 (5px)', 'Medium (5px)')}</option>
            <option value={10}>{t('低 (10px)', 'Low (10px)')}</option>
          </select>
        </div>
      </div>

      <div className="captcha-box">
        <SliderCaptcha
          ref={captchaRef}
          width={320}
          height={180}
          precision={precision}
          locale={currentLocale}
          onSuccess={() => { console.log('Slider success'); updateStats() }}
        />
      </div>

      <div className="btn-group">
        <button className="btn btn-primary" onClick={() => captchaRef.current?.refresh()}>
          {t('重置验证码', 'Reset')}
        </button>
        <button className="btn btn-secondary" onClick={() => {
          console.log('Slider data:', captchaRef.current?.getData())
          alert(t('验证数据已输出到控制台', 'Data logged to console'))
        }}>
          {t('获取数据', 'Get Data')}
        </button>
        <button className="btn btn-secondary" onClick={updateStats}>
          {t('查看统计', 'Statistics')}
        </button>
      </div>

      {stats && (
        <div className="stats">
          <div className="stat-item">
            <span className="stat-value">{stats.totalAttempts}</span>
            <span className="stat-label">{t('总尝试', 'Attempts')}</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">{stats.successCount}</span>
            <span className="stat-label">{t('成功', 'Success')}</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">{stats.successRate}%</span>
            <span className="stat-label">{t('成功率', 'Rate')}</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">{stats.avgVerifyTime}ms</span>
            <span className="stat-label">{t('平均耗时', 'Avg Time')}</span>
          </div>
        </div>
      )}
    </section>
  )
}
