// packages/taro-react/src/components/ClickCaptcha.tsx
import type { ClickCaptchaProps, ClickCaptchaRef, Point } from '../types'
import { DEFAULT_LOCALE, getLocaleMessage } from '@captcha-pro/mp-shared'
import { Image, Text, View } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import { fetchCaptcha, verifyCaptcha } from '../request'
import '../styles/captcha.scss'

const ClickCaptcha = forwardRef<ClickCaptchaRef, ClickCaptchaProps>(({
  width = 650, height = 380, showRefresh = true, backend, onSuccess, onFail, onRefresh, onError,
}, ref) => {
  const t = (key: string): string => getLocaleMessage(DEFAULT_LOCALE, key)

  const [captchaId, setCaptchaId] = useState('')
  const [bgImage, setBgImage] = useState('')
  const [clickTexts, setClickTexts] = useState<string[]>([])
  const [clickCharImages, setClickCharImages] = useState<string[]>([])
  const [status, setStatus] = useState<'' | 'success' | 'fail'>('')
  const [clickMarkers, setClickMarkers] = useState<Array<Point & { index: number }>>([])
  const [loading, setLoading] = useState(true)
  const [errorMsg, setErrorMsg] = useState('')
  const loadSeqRef = useRef(0)
  const onSuccessRef = useRef(onSuccess)
  const onFailRef = useRef(onFail)
  const onRefreshRef = useRef(onRefresh)
  const onErrorRef = useRef(onError)

  useEffect(() => {
    onSuccessRef.current = onSuccess
    onFailRef.current = onFail
    onRefreshRef.current = onRefresh
    onErrorRef.current = onError
  }, [onSuccess, onFail, onRefresh, onError])

  const rpxToPx = useCallback((rpx: number) => Math.floor(rpx * Taro.getWindowInfo().screenWidth / 750), [])
  const widthPx = useMemo(() => rpxToPx(width), [width, rpxToPx])
  const heightPx = useMemo(() => rpxToPx(height), [height, rpxToPx])

  const loadCaptcha = useCallback(async () => {
    const seq = ++loadSeqRef.current
    setLoading(true)
    setErrorMsg('')
    setStatus('')
    setClickMarkers([])
    setClickTexts([])
    setClickCharImages([])
    try {
      const res = await fetchCaptcha(backend, { type: 'click', width: widthPx, height: heightPx })
      if (seq !== loadSeqRef.current) return
      if (!res.success || !res.data) throw new Error(res.message || 'Failed')
      setCaptchaId(res.data.captchaId)
      setBgImage(res.data.bgImage)
      setClickTexts(res.data.clickTexts ?? [])
      setClickCharImages(res.data.clickCharImages ?? [])
    } catch (err) {
      if (seq !== loadSeqRef.current) return
      const error = err instanceof Error ? err : new Error(String(err))
      setErrorMsg(error.message)
      onError?.(error)
    } finally {
      if (seq === loadSeqRef.current) setLoading(false)
    }
  }, [backend, widthPx, heightPx, onError])

  useEffect(() => { if (widthPx && heightPx) loadCaptcha() }, [widthPx, heightPx, loadCaptcha])

  const handleClick = useCallback((e: any) => {
    if (status || loading || clickMarkers.length >= clickTexts.length) return
    const touch = e.touches?.[0] || e.detail
    if (!touch) return
    Taro.createSelectorQuery().select('.captcha-area').boundingClientRect((rect: any) => {
      if (!rect) return
      const newMarkers = [...clickMarkers, { x: touch.clientX - rect.left, y: touch.clientY - rect.top, index: clickMarkers.length + 1 }]
      setClickMarkers(newMarkers)
      if (newMarkers.length >= clickTexts.length) {
        setTimeout(async () => {
          setLoading(true)
          try {
            const res = await verifyCaptcha(backend, { captchaId, type: 'click', target: newMarkers.map(m => ({ x: m.x, y: m.y })) })
            if (res.success) {
              setStatus('success')
              onSuccessRef.current?.(res.data)
            } else {
              setStatus('fail')
              onFailRef.current?.()
              setTimeout(() => { loadCaptcha(); onRefreshRef.current?.() }, 800)
            }
          } catch (err) {
            console.error('[ClickCaptcha] 错误', err)
            setStatus('fail')
            setTimeout(loadCaptcha, 800)
          } finally { setLoading(false) }
        }, 200)
      }
    }).exec()
  }, [status, loading, clickMarkers, clickTexts, captchaId, backend, loadCaptcha])

  const refresh = useCallback(() => { loadCaptcha(); onRefreshRef.current?.() }, [loadCaptcha])

  // Expose refresh method via ref
  useImperativeHandle(ref, () => ({ refresh }), [refresh])

  return (
    <View class="captcha-container">
      <View class="captcha-area" role="button" aria-label={t('click_prompt')} style={{ width: `${widthPx}px`, height: `${heightPx}px` }} onClick={handleClick}>
        {bgImage ? <Image src={bgImage} mode="aspectFill" class="bg-image" style={{ width: `${widthPx}px`, height: `${heightPx}px` }} /> : <View class="captcha-loading"><Text>{errorMsg || '加载中...'}</Text></View>}
        {clickMarkers.map(m => (
          <View key={m.index} class="click-marker" aria-label={String(m.index)} style={{ left: `${m.x}px`, top: `${m.y}px` }}>
            <Text class="marker-text">{m.index}</Text>
          </View>
        ))}
        {showRefresh && !loading && (
          <View class="refresh-btn" role="button" aria-label={t('refresh')} onClick={e => { e.stopPropagation(); refresh() }}>
            <Text class="refresh-icon">⟳</Text>
          </View>
        )}
        {status && (
          <View class={`status-overlay ${status}`} aria-live="polite" aria-atomic="true">
            <View class="status-icon"><Text>{status === 'success' ? '✓' : '✕'}</Text></View>
            <Text class="status-text">{status === 'success' ? '验证成功' : '验证失败'}</Text>
          </View>
        )}
      </View>
      <View class="prompt-bar" style={{ width: `${widthPx}px` }}>
        <Text class="prompt-text">请依次点击：</Text>
        <View class="prompt-chars">
          {clickCharImages.length > 0 ? clickCharImages.map(img => (
            <View key={img} class="char-item">
              <Image src={img} class="char-img" mode="aspectFit" />
            </View>
          )) : clickTexts.map(char => (
            <View key={char} class="char-item">
              <Text class="char-text">{char}</Text>
            </View>
          ))}
        </View>
      </View>
    </View>
  )
})

ClickCaptcha.displayName = 'ClickCaptcha'

export default ClickCaptcha

// packages/taro-vue/src/components/click-captcha.vue
<script setup lang="ts">
import { Image, Text, View } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useClickCaptcha } from '../composables/useClickCaptcha'
import { DEFAULT_CLICK_COUNT, DEFAULT_LOCALE, getLocaleMessage, type ClickCaptchaProps } from '@captcha-pro/mp-shared'
import '../styles/captcha.scss'

const props = withDefaults(defineProps<ClickCaptchaProps>(), {
	width: 650,
	height: 380,
	showRefresh: true,
	locale: DEFAULT_LOCALE,
})

const t = (key: string) => getLocaleMessage(props.locale, key)

const {
	bgImage,
	status,
	loading,
	errorMsg,
	clickPoints,
	clickTexts,
	clickCharImages,
	setClickTexts,
	setClickCharImages,
	refresh,
	addClickPoint,
	verify,
	rpxToPx,
	widthPx,
	heightPx,
} = useClickCaptcha(props.backend, {
	width: props.width,
	height: props.height,
	onSuccess: props.onSuccess,
	onFail: props.onFail,
	onRefresh: props.onRefresh,
	onError: props.onError,
})

const handleClick = (e: any) => {
	if (status.value || loading.value) return
	const maxClicks = clickTexts.value.length || DEFAULT_CLICK_COUNT
	if (clickPoints.value.length >= maxClicks) return

	const touch = e.touches?.[0] || e.detail
	if (!touch) return

	const query = Taro.createSelectorQuery()
	query.select('.captcha-area').boundingClientRect((rect: any) => {
		if (!rect) return
		const x = touch.clientX - rect.left
		const y = touch.clientY - rect.top
		addClickPoint({ x, y })
		if (clickPoints.value.length >= maxClicks) {
			setTimeout(verify, 200)
		}
	}).exec()
}

defineExpose({ refresh })
</script>

<template>
  <View class="captcha-container">
    <View
      class="captcha-area"
      :style="{
        width: `${widthPx}px`,
        height: `${heightPx}px`,
        borderRadius: '16rpx',
      }"
      role="button"
      :aria-label="t('click_prompt')"
      @click="handleClick"
    >
      <Image
        v-if="bgImage"
        :src="bgImage"
        mode="aspectFill"
        class="bg-image"
        :style="{ width: `${widthPx}px`, height: `${heightPx}px` }"
      />
      <View
        v-else
        class="captcha-loading"
        :style="{ width: `${widthPx}px`, height: `${heightPx}px` }"
      >
        <Text>{{ errorMsg || t('loading') }}</Text>
      </View>

      <View
        v-for="(marker, idx) in clickPoints"
        :key="idx"
        class="click-marker"
        :style="{ left: `${marker.x}px`, top: `${marker.y}px` }"
        :aria-label="String(idx + 1)"
      >
        <Text class="marker-text">{{ idx + 1 }}</Text>
      </View>

      <View v-if="showRefresh && !loading" class="refresh-btn" role="button" :aria-label="t('refresh')" @click.stop="refresh">
        <Text class="refresh-icon">⟳</Text>
      </View>

      <View v-if="status" class="status-overlay" :class="status" aria-live="polite" aria-atomic="true">
        <View class="status-icon"><Text>{{ status === 'success' ? '✓' : '✕' }}</Text></View>
        <Text class="status-text">{{ status === 'success' ? t('click_success') : t('click_fail') }}</Text>
      </View>
    </View>

    <View class="prompt-bar" :style="{ width: `${widthPx}px` }">
      <Text class="prompt-text">{{ t('click_prompt') }}</Text>
      <View class="prompt-chars">
        <template v-if="clickCharImages.length > 0">
          <View v-for="(img, i) in clickCharImages" :key="`img${i}`" class="char-item">
            <Image :src="img" class="char-img" mode="aspectFit" />
          </View>
        </template>
        <template v-else>
          <View v-for="(char, i) in clickTexts" :key="`txt${i}`" class="char-item">
            <Text class="char-text">{{ char }}</Text>
          </View>
        </template>
      </View>
    </View>
  </View>
</template>
